---
name: Tests and checks

on:
  push:
    branches:
      - '**'
      - '!master'
    paths-ignore:
      - '.circleci/**'
      - '.github/**'
      - '!.github/workflows/tests-and-checks.yml'
      - '.k8s/**'
      - '.vscode/**'
      - '*.md'
  schedule:
    - cron: '0 1 * * 0'

permissions:
  contents: read

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@dd0578b371c987f96d1185abb54344b44352bd58 # v1
        with:
          go-version-input: 1.22.3

  tests:
    strategy:
      matrix:
        go: [ '~1.21', '~1.22' ]
    runs-on: ubuntu-latest
    name: Run tests with go version ${{ matrix.go }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go }}

      - run: go test -v -fuzz FuzzHandler -fuzztime 50x ./handlers/ip/
