---
name: Tests and checks

on:
  push:
    branches:
      - '**'
      - '!master'
    paths-ignore:
      - '.circleci/**'
      - '.github/**'
      - '!.github/workflows/tests-and-checks.yml'
      - '.k8s/**'
      - '.vscode/**'
      - '*.md'
  schedule:
    - cron: '0 1 * * 0'

permissions:
  contents: read

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1
        with:
          go-version-input: 1.23

  tests:
    strategy:
      matrix:
        go: [ '~1.22', '~1.23' ]
    runs-on: ubuntu-latest
    name: Run tests with go version ${{ matrix.go }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: ${{ matrix.go }}

      - run: go test -v -fuzz FuzzHandler -fuzztime 50x ./handlers/ip/
